# Generated by Django 4.2.23 on 2025-08-28 07:26

import apps.category_skills.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(help_text='Enter Description For Particular Course', max_length=999)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.category_skills.models.category_skills)),
                ('description', models.TextField(help_text='Enter Description for Specific Skill', max_length=999)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='category_skills.skillscategory')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'db_table': 'category_skills',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
