# Generated by Django 4.2.23 on 2025-08-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='teacher',
        ),
    ]
