# Generated by Django 4.2.23 on 2025-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0002_remove_skills_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillscategory',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
