# Generated by Django 4.2.23 on 2025-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_skills', '0003_skillscategory_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='Beginner', max_length=25),
        ),
    ]
